name = "CSV"
uuid = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
authors = ["Jacob Quinn <quinn.jacobd@gmail.com>"]
version = "0.6.2"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
Parsers = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
PooledArrays = "2dfb63ee-cc39-5dd5-95bd-886bf059d720"
SentinelArrays = "91c51154-3ec4-41a3-a24f-3f23e20d615c"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
WeakRefStrings = "ea10d353-3f73-51f8-a26c-33c1cb351aa5"

[compat]
CategoricalArrays = "0.8"
DataFrames = "0.21"
DecFP = "1"
FilePathsBase = "0.6,0.7,0.8,0.9"
Parsers = "1"
PooledArrays = "0.5"
Tables = "1"
WeakRefStrings = "0.5,0.6"
julia = "1"

[extras]
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
DecFP = "55939f99-70c6-5e9b-8bb0-5071ed7d61fd"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DecFP", "Test", "Random", "CodecZlib"]
