name = "CSV"
uuid = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
authors = ["Jacob Quinn <quinn.jacobd@gmail.com>"]
version = "0.10.15"

[deps]
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
InlineStrings = "842dd82b-1e85-43dc-bf29-5d0ee9dffc48"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
Parsers = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
PooledArrays = "2dfb63ee-cc39-5dd5-95bd-886bf059d720"
SentinelArrays = "91c51154-3ec4-41a3-a24f-3f23e20d615c"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
WeakRefStrings = "ea10d353-3f73-51f8-a26c-33c1cb351aa5"
WorkerUtilities = "76eceee3-57b5-4d4a-8e66-0e911cebbf60"

[compat]
CodecZlib = "0.7"
FilePathsBase = "0.6,0.7,0.8,0.9"
InlineStrings = "1"
Parsers = "2.5"
PooledArrays = "0.5, 1.0"
SentinelArrays = "1.2"
PrecompileTools = "1"
Tables = "1.1"
WeakRefStrings = "1.4"
WorkerUtilities = "1.6"
julia = "1.6"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
